### ISSUE TITLE
Client Crash when using Letter Block

### ISSUE THREAD

**Issue by Inscrutable** [AlmuraDev/ServerContent#14]
Repeated crashes just handling the blocks. Holding "A" causes instant crash on login. Almura b64.
(With Journeymap, if it matters). VBO's off. [Edit] Happens with and without Dynamic Lights on.
https://gist.github.com/Inscrutable/dbd87e1844126ace7b529e29935582bd

**Comment by Inscrutable** [comment]
I get the same issue with Almura build 65. It does not like my trying to place the A in FLARD.
https://gist.github.com/Inscrutable/ea13c0124ebdb66cfa46e4631f024723

**Comment by Dockter** [comment]
Fix coming with: https://github.com/AlmuraDev/ServerContent/commit/33fbf525d836615a44b0d2d62ed6b750ce9f68e9
