### ISSUE TITLE
All Almura Blocks Are Glass Or A Type Of Glass Or Just Act Like Glass

### ISSUE THREAD

**Issue by PowellA12** [AlmuraDev/ServerContent#8]
1.light can pass though
2.does not kill you when inside of the block
3. can't place redstone (also doc your fix for the torches is not a fix it's a pach just for torches and it does not work well )
4.redstone see it as glass because redstone can't go though the block
5.always rendered <yes doc did fix this but still i need five not four four is just lame

**Comment by Inscrutable** [comment]
6. Doors can't be placed on them
7. Mobs spawn on/in them regardless of light level
8. Rain always renders *behind* morbus trees, not in front of them
9. Lighting on them is wacky and inconsistent.

**Comment by Dockter** [comment]
OK, finally getting some time to tinker with this.

I am onto the trail of fixing this.  Thank you both of you, the information you provided helped me nail down where this is wrong.

**Comment by Dockter** [comment]
Fixed the door issue.
Fixed the lighting issue on non-horizontal blocks.
Fixed rendering.
